[2024-09-05T11:48:23.840+0530] {processor.py:186} INFO - Started process (PID=32462) to work on /mnt/c/Users/yatish.v/Desktop/New folder (2)/dags/dag.py
[2024-09-05T11:48:23.842+0530] {processor.py:914} INFO - Processing file /mnt/c/Users/yatish.v/Desktop/New folder (2)/dags/dag.py for tasks to queue
[2024-09-05T11:48:23.846+0530] {logging_mixin.py:190} INFO - [2024-09-05T11:48:23.844+0530] {dagbag.py:587} INFO - Filling up the DagBag from /mnt/c/Users/yatish.v/Desktop/New folder (2)/dags/dag.py
[2024-09-05T11:48:23.997+0530] {logging_mixin.py:190} INFO - [2024-09-05T11:48:23.951+0530] {dagbag.py:386} ERROR - Failed to import: /mnt/c/Users/yatish.v/Desktop/New folder (2)/dags/dag.py
Traceback (most recent call last):
  File "/mnt/c/Users/yatish.v/Desktop/New folder (2)/airflow_env/lib/python3.10/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/mnt/c/Users/yatish.v/Desktop/New folder (2)/dags/dag.py", line 4, in <module>
    from sklearn.datasets import load_iris
ModuleNotFoundError: No module named 'sklearn'
[2024-09-05T11:48:24.001+0530] {processor.py:927} WARNING - No viable dags retrieved from /mnt/c/Users/yatish.v/Desktop/New folder (2)/dags/dag.py
[2024-09-05T11:48:24.191+0530] {processor.py:208} INFO - Processing /mnt/c/Users/yatish.v/Desktop/New folder (2)/dags/dag.py took 0.371 seconds
[2024-09-05T11:48:43.003+0530] {processor.py:186} INFO - Started process (PID=32562) to work on /mnt/c/Users/yatish.v/Desktop/New folder (2)/dags/dag.py
[2024-09-05T11:48:43.005+0530] {processor.py:914} INFO - Processing file /mnt/c/Users/yatish.v/Desktop/New folder (2)/dags/dag.py for tasks to queue
[2024-09-05T11:48:43.009+0530] {logging_mixin.py:190} INFO - [2024-09-05T11:48:43.008+0530] {dagbag.py:587} INFO - Filling up the DagBag from /mnt/c/Users/yatish.v/Desktop/New folder (2)/dags/dag.py
[2024-09-05T11:48:43.098+0530] {logging_mixin.py:190} INFO - [2024-09-05T11:48:43.077+0530] {dagbag.py:386} ERROR - Failed to import: /mnt/c/Users/yatish.v/Desktop/New folder (2)/dags/dag.py
Traceback (most recent call last):
  File "/mnt/c/Users/yatish.v/Desktop/New folder (2)/airflow_env/lib/python3.10/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/mnt/c/Users/yatish.v/Desktop/New folder (2)/dags/dag.py", line 4, in <module>
    from sklearn.datasets import load_iris
ModuleNotFoundError: No module named 'sklearn'
[2024-09-05T11:48:43.102+0530] {processor.py:927} WARNING - No viable dags retrieved from /mnt/c/Users/yatish.v/Desktop/New folder (2)/dags/dag.py
[2024-09-05T11:48:43.246+0530] {processor.py:208} INFO - Processing /mnt/c/Users/yatish.v/Desktop/New folder (2)/dags/dag.py took 0.267 seconds
[2024-09-05T11:49:45.414+0530] {processor.py:186} INFO - Started process (PID=32881) to work on /mnt/c/Users/yatish.v/Desktop/New folder (2)/dags/dag.py
[2024-09-05T11:49:45.417+0530] {processor.py:914} INFO - Processing file /mnt/c/Users/yatish.v/Desktop/New folder (2)/dags/dag.py for tasks to queue
[2024-09-05T11:49:45.420+0530] {logging_mixin.py:190} INFO - [2024-09-05T11:49:45.419+0530] {dagbag.py:587} INFO - Filling up the DagBag from /mnt/c/Users/yatish.v/Desktop/New folder (2)/dags/dag.py
[2024-09-05T11:49:45.456+0530] {logging_mixin.py:190} INFO - [2024-09-05T11:49:45.445+0530] {dagbag.py:386} ERROR - Failed to import: /mnt/c/Users/yatish.v/Desktop/New folder (2)/dags/dag.py
Traceback (most recent call last):
  File "/mnt/c/Users/yatish.v/Desktop/New folder (2)/airflow_env/lib/python3.10/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/mnt/c/Users/yatish.v/Desktop/New folder (2)/dags/dag.py", line 4, in <module>
    from sklearn.datasets import load_iris
ModuleNotFoundError: No module named 'sklearn'
[2024-09-05T11:49:45.459+0530] {processor.py:927} WARNING - No viable dags retrieved from /mnt/c/Users/yatish.v/Desktop/New folder (2)/dags/dag.py
[2024-09-05T11:49:45.638+0530] {processor.py:208} INFO - Processing /mnt/c/Users/yatish.v/Desktop/New folder (2)/dags/dag.py took 0.243 seconds
[2024-09-05T11:51:05.977+0530] {processor.py:186} INFO - Started process (PID=33287) to work on /mnt/c/Users/yatish.v/Desktop/New folder (2)/dags/dag.py
[2024-09-05T11:51:05.980+0530] {processor.py:914} INFO - Processing file /mnt/c/Users/yatish.v/Desktop/New folder (2)/dags/dag.py for tasks to queue
[2024-09-05T11:51:05.983+0530] {logging_mixin.py:190} INFO - [2024-09-05T11:51:05.982+0530] {dagbag.py:587} INFO - Filling up the DagBag from /mnt/c/Users/yatish.v/Desktop/New folder (2)/dags/dag.py
[2024-09-05T11:51:06.017+0530] {logging_mixin.py:190} INFO - [2024-09-05T11:51:06.004+0530] {dagbag.py:386} ERROR - Failed to import: /mnt/c/Users/yatish.v/Desktop/New folder (2)/dags/dag.py
Traceback (most recent call last):
  File "/mnt/c/Users/yatish.v/Desktop/New folder (2)/airflow_env/lib/python3.10/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/mnt/c/Users/yatish.v/Desktop/New folder (2)/dags/dag.py", line 4, in <module>
    from sklearn.datasets import load_iris
ModuleNotFoundError: No module named 'sklearn'
[2024-09-05T11:51:06.020+0530] {processor.py:927} WARNING - No viable dags retrieved from /mnt/c/Users/yatish.v/Desktop/New folder (2)/dags/dag.py
[2024-09-05T11:51:06.343+0530] {processor.py:208} INFO - Processing /mnt/c/Users/yatish.v/Desktop/New folder (2)/dags/dag.py took 0.384 seconds
[2024-09-05T11:52:51.590+0530] {processor.py:186} INFO - Started process (PID=33780) to work on /mnt/c/Users/yatish.v/Desktop/New folder (2)/dags/dag.py
[2024-09-05T11:52:51.748+0530] {processor.py:914} INFO - Processing file /mnt/c/Users/yatish.v/Desktop/New folder (2)/dags/dag.py for tasks to queue
[2024-09-05T11:52:51.807+0530] {logging_mixin.py:190} INFO - [2024-09-05T11:52:51.773+0530] {dagbag.py:587} INFO - Filling up the DagBag from /mnt/c/Users/yatish.v/Desktop/New folder (2)/dags/dag.py
[2024-09-05T11:52:53.239+0530] {logging_mixin.py:190} INFO - [2024-09-05T11:52:52.738+0530] {dagbag.py:386} ERROR - Failed to import: /mnt/c/Users/yatish.v/Desktop/New folder (2)/dags/dag.py
Traceback (most recent call last):
  File "/mnt/c/Users/yatish.v/Desktop/New folder (2)/airflow_env/lib/python3.10/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/mnt/c/Users/yatish.v/Desktop/New folder (2)/dags/dag.py", line 4, in <module>
    from sklearn.datasets import load_iris
ModuleNotFoundError: No module named 'sklearn'
[2024-09-05T11:52:53.266+0530] {processor.py:927} WARNING - No viable dags retrieved from /mnt/c/Users/yatish.v/Desktop/New folder (2)/dags/dag.py
[2024-09-05T11:52:55.302+0530] {processor.py:208} INFO - Processing /mnt/c/Users/yatish.v/Desktop/New folder (2)/dags/dag.py took 4.023 seconds
